---
# handlers file for vese-kodi
- name: Reboot
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: systemctl is-active --quiet kodi
- name: Restart Kodi
  ansible.builtin.systemd:
    name: kodi
    state: restarted