---
- name: "Install Kodi Plugins"
  block:
  - name: Download zip InputStreamHelper
    ansible.builtin.get_url:
      url: " {{ vese_kodi_inputstreamhelper_url }}"
      dest: "{{ ansible_env.HOME }}"
      mode: '0755'
    register: vese_kodi_inputstreamhelper_filename
  - name: Extract InputStreamHelper zip to addons dir
    ansible.builtin.unarchive:
      src: "{{ vese_kodi_inputstreamhelper_filename.dest }}"
      dest: '{{ vese_kodi_home_dir }}/.kodi/addons/'
      remote_src: yes
      creates: '{{ vese_kodi_home_dir }}/.kodi/addons/script.module.inputstreamhelper'
  - name: Clone plugins
    ansible.builtin.git:
      repo: '{{ item.url }}'
      dest: '{{ vese_kodi_home_dir }}/.kodi/addons/{{ repo_name }}'
      version: '{{ item.version }}'
    loop: '{{ vese_kodi_plugins }}'
    vars:
      repo_name: "{{ item.url.split('/') | last | replace('.git', '') }}"
    register: vese_kodi_plugin_install
    become: true
    become_user: kodi
    failed_when:
      - vese_kodi_plugin_install.failed
      - not 'Local modifications exist in repository' in vese_kodi_plugin_install.msg
  notify: Restart Kodi
- copy:
    src: favourites.xml
    dest: '{{ vese_kodi_home_dir }}/favourites.xml'
    owner: kodi
    group: kodi
    mode: u=rw,g=r,o=r

