---
- name: Clone kodi-standalone repository
  ansible.builtin.git:
    repo: '{{ vese_kodi_standalone_repo }}'
    dest: '{{ vese_kodi_local_git_path }}'
    version: '{{ vese_kodi_standalone_version }}'
  register: vese_kodi_standalone_release


